spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/hotel_auth?

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  token:
    validity:
      refresh: 10080
      access: 120
  oauth2:
    client:
      accessTokenUri: http://localhost:5000/api/uaa/oauth/token
      resource:
        user-info-uri: http://localhost:5000/api/uaa/user/info
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAohBdsn9EZxlDXQIZ3rj0
          +jc+9HbQkjQzdsLooFrpYYZ3pfaPyrtrVfd7njiCDitVEQ7zYI24GkhVtQq/XjyH
          Aqm2Rsz1vIT7/ZfcQmdEsNG425XmlIwvBD3GHiR/zEPzsn2Inz08hRguGFo9cOQj
          UYYGV7cnQEBlXBf/biSMynNrx0DJNdtiC6R+zki1MzoTDbFEnrhKoxAeIaew2YPL
          OYVXn13IUauGq79sRqLPc5VNoHEb1CTN/St7JnD42wwrchGRJCC3Avurj5ZCCDXQ
          v5R/7FHGn2wzzbkfDyz23ogrzBbHBPufIcPSKhwXQ60EG6vKngh8cJUvGhTHkBG7
          2QIDAQAB
          -----END PUBLIC KEY-----

logging:
  file: hotel/auth-service.log

