spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/hotel_activity?
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file: hotel/activity-service.log