
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  routes:
    simple-service:
      path: /simple/**
      serviceId: simple-service
      sensitiveHeaders:
    auth-service-uaa:
      path: /uaa/**
      serviceId: auth-service
      sensitiveHeaders:
    activity-service:
      path: /activity/**
      serviceId: activity-service
      sensitiveHeaders:


logging:
  file: hotel/proxy-service.log